"""Add question field to knowledge_points table

Revision ID: 913d2f368114
Revises: b8aed852ba4f
Create Date: 2025-08-01 09:20:26.509274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913d2f368114'
down_revision = 'b8aed852ba4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_sessions_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_learning_answers_id'), table_name='learning_answers')
    op.drop_table('learning_answers')
    op.add_column('knowledge_points', sa.Column('question', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_points', 'question')
    op.create_table('learning_answers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('knowledge_point_id', sa.INTEGER(), nullable=False),
    sa.Column('user_answer', sa.TEXT(), nullable=False),
    sa.Column('evaluation', sa.TEXT(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('answered_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_answers_id'), 'learning_answers', ['id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('session_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('knowledge_point_ids', sa.TEXT(), nullable=False),
    sa.Column('current_index', sa.INTEGER(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_id'), 'learning_sessions', ['id'], unique=False)
    # ### end Alembic commands ###
